apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kvib
  tags:
    - public
spec:
  type: website
  lifecycle: production
  owner: designsystem

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kvib-react
  tags:
    - public
spec:
  type: library
  owner: group:default/designsystem
  lifecycle: production
