/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "KVIB",
  "tagline": "Kartverkets designsystem",
  "url": "https://kartverket.github.io",
  "baseUrl": "/kvib/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "staticDirectories": [
    "src/js",
    "static"
  ],
  "organizationName": "kartverket",
  "projectName": "kvib",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "no",
    "locales": [
      "no"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "stylesheets": [
    {
      "href": "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\nilben\\dev\\kvib\\apps\\docusaurus\\sidebars.js",
          "routeBasePath": "/"
        },
        "blog": {
          "showReadingTime": false,
          "blogTitle": "KVIB Versjoner",
          "blogDescription": "En oversikt over versjoner av KVIB",
          "postsPerPage": "ALL",
          "blogSidebarTitle": "Alle versjoner",
          "blogSidebarCount": "ALL"
        },
        "theme": {
          "customCss": "C:\\Users\\nilben\\dev\\kvib\\apps\\docusaurus\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": false
      },
      "versionPersistence": "localStorage"
    },
    "algolia": {
      "appId": "5F5HK7A36S",
      "apiKey": "13e6147634622624bf57712cbc4e9c8d",
      "indexName": "kvib",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "metadata": [
      {
        "name": "color-scheme",
        "content": "light only"
      }
    ],
    "navbar": {
      "logo": {
        "alt": "Kartverket logo",
        "src": "img/logo/kvib_logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "omKvib/infoKvibID",
          "position": "right",
          "label": "Kom i gang"
        },
        {
          "to": "designsystem/Komponenter",
          "position": "right",
          "label": "Komponenter"
        },
        {
          "to": "designsystem/designTokens",
          "position": "right",
          "label": "Tokens"
        },
        {
          "to": "designsystems/uu",
          "position": "right",
          "label": "Universell utforming"
        },
        {
          "to": "blog",
          "label": "Versjoner",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Kartverket KVIB Logo",
        "src": "img/logo/kartverket_liggende.png"
      },
      "links": [
        {
          "title": "Nyttige sider",
          "items": [
            {
              "label": "Om KVIB",
              "to": "/omkvib"
            },
            {
              "label": "Installasjon",
              "to": "/omKvib/implementering"
            },
            {
              "label": "Utvide KVIB",
              "to": "/utvideKvib"
            }
          ]
        },
        {
          "title": "GitHub",
          "items": [
            {
              "label": "KVIB",
              "href": "https://github.com/kartverket/kvib"
            }
          ]
        },
        {
          "title": "Kontakt",
          "items": [
            {
              "label": "#gen-kvib på slack",
              "href": "https://slack.com/app_redirect?channel=gen-kvib"
            },
            {
              "label": "Send oss en epost",
              "href": "mailto:kvib-feedbacks-aaaahwh252gnftmofucpaa47ca@kartverketgroup.slack.com?subject=KVIB Feedback"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 KVIB."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
