export {
  EditableRoot as Editable,
  EditableArea,
  EditableCancelTrigger,
  EditableContext,
  EditableControl,
  EditableEditTrigger,
  EditableInput,
  EditablePreview,
  EditableRoot,
  EditableRootProvider,
  EditableSubmitTrigger,
  EditableTextarea,
  Editable as KvibEditable,
  useEditable,
  useEditableContext,
  useEditableStyles,
} from "@chakra-ui/react";

export type {
  EditableAreaProps,
  EditableCancelTriggerProps,
  EditableControlProps,
  EditableEditTriggerProps,
  EditableInputProps,
  EditablePreviewProps,
  EditableRootProps as EditableProps,
  EditableRootProps,
  EditableSubmitTriggerProps,
  EditableTextareaProps,
  EditableValueChangeDetails,
} from "@chakra-ui/react";
