export {
  ColorPickerRoot as ColorPicker,
  ColorPickerArea,
  ColorPickerChannelInput,
  ColorPickerChannelInputs,
  ColorPickerChannelSlider,
  ColorPickerChannelSliders,
  ColorPickerContent,
  ColorPickerControl,
  ColorPickerEyeDropper,
  ColorPickerInlineContent,
  ColorPickerInput,
  ColorPickerLabel,
  ColorPickerRoot,
  ColorPickerSliders,
  ColorPickerSwatchGroup,
  ColorPickerSwatchTrigger,
  ColorPickerTrigger,
  ColorPickerValueSwatch,
  ColorPickerValueText,
} from "@/components/ui/color-picker";

export { ColorPicker as KvibColorPicker } from "@chakra-ui/react";

export type {
  ColorPickerAreaBackgroundProps,
  ColorPickerAreaProps,
  ColorPickerAreaThumbProps,
  ColorPickerChannelInputProps,
  ColorPickerContentProps,
  ColorPickerControlProps,
  ColorPickerFormatSelectProps,
  ColorPickerLabelProps,
  ColorPickerPositionerProps,
  ColorPickerRootProps as ColorPickerProps,
  ColorPickerRootProps,
  ColorPickerSwatchGroupProps,
  ColorPickerSwatchProps,
  ColorPickerTriggerProps,
  ColorPickerValueTextProps,
  ColorPickerViewProps,
} from "@chakra-ui/react";
