/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],

  mainSidebar: [{
    type: 'category',
    label:'Hoved' ,
    items: ['figmaID']
  }],

  designsystemSidebar: [{type: 'autogenerated', dirName:'designsystems'}]

  // But you can create a sidebar manually

  /*customSidebar: [{
      type: 'category',
      label: 'Custom Sidebar Test',
      items: ['farger-id', 'grids-id']
    },
  ],*/

};

module.exports = sidebars;
